# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target '每诺鲜' do

pod 'SDWebImage'
pod 'YYModel'
pod 'Masonry'
pod 'AFNetworkActivityLogger'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MJExtension'

end
